# Generated by Django 4.0.3 on 2022-03-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='name',
        ),
    ]
