# Generated by Django 4.0.3 on 2022-03-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapi', '0002_rename_first_name_person_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='first_name',
        ),
    ]
