# Generated by Django 4.0.3 on 2022-03-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapi', '0003_rename_name_person_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=11)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
